In [18]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [19]:
raw_df = pd.read_excel('sales_data.xlsx')
print(f'{raw_df.shape[0]} rows, {raw_df.shape[1]} columns')
raw_df.head(10)

30 rows, 9 columns

,order_id,customer_name,product,category,quantity,unit_price,order_date,city,sales_rep
0,1001,Ramesh Kumar,Laptop,Electronics,2.0,45000,2024-01-05,Mumbai,Anil Sharma
1,1002,Priya Nair,NaN,Electronics,1.0,15000,2024-01-07,Delhi,Sunita Rao
2,1003,AMIT VERMA,Keyboard,Accessories,3.0,1200,2024-01-08,Bangalore,Anil Sharma
3,1004,Sunita Patel,Monitor,Electronics,NaN,22000,2024-01-10,Chennai,Ravi Kumar
4,1005,Ramesh Kumar,Laptop,Electronics,2.0,45000,2024-01-05,Mumbai,Anil Sharma
5,1006,kiran mehta,Mouse,Accessories,10.0,800,07-01-2024,Pune,Sunita Rao
6,1007,Deepak Singh,Headphones,Electronics,2.0,3500,2024-01-12,Hyderabad,Ravi Kumar
7,1008,NaN,Webcam,Accessories,1.0,2500,2024-01-13,Mumbai,Anil Sharma
8,1009,Ananya Das,Laptop,Electronics,1.0,45000,2024-01-15,Kolkata,Sunita Rao
9,1010,Vikram Iyer,Keyboard,Accessories,5.0,1200,2024-01-15,Chennai,Ravi Kumar

In [20]:
print('Missing values:')
print(raw_df.isnull().sum())
print(f'\nDuplicates: {raw_df.duplicated().sum()}')
print(f'\nTypes:\n{raw_df.dtypes}')

Missing values:
order_id         0
customer_name    2
product          1
category         1
quantity         3
unit_price       0
order_date       0
city             0
sales_rep        0
dtype: int64

Duplicates: 0

Types:
order_id           int64
customer_name     object
product           object
category          object
quantity         float64
unit_price         int64
order_date        object
city              object
sales_rep         object
dtype: object

In [ ]:
df = raw_df.copy()
print(f'Working copy: {df.shape}')

Working copy created: (30, 9)

In [22]:
before = df.isnull().sum().sum()

df['customer_name'].fillna('Unknown', inplace=True)
df['product'].fillna('Unknown', inplace=True)
df['category'].fillna('Other', inplace=True)
df['quantity'].fillna(df['quantity'].median(), inplace=True)
df['city'].fillna('Unknown', inplace=True)

after = df.isnull().sum().sum()
print(f'Nulls values : Before {before} -> After {after}')

Nulls values : Before 0 -> After 0

In [25]:
before = len(df)
df.drop_duplicates(inplace=True)
print(f'Duplicate Rows: Before {before} -> After {len(df)} removed {before - len(df)} duplicates')

Duplicate Rows: Before 30 -> After 30 removed 0 duplicates

In [26]:
df.columns = df.columns.str.lower().str.replace(' ', '_').str.replace('-', '_')

In [ ]:
df['total_amount'] = df['quantity'] * df['unit_price']
print('Amount calculated')

0    90000.0
1    15000.0
2     3600.0
3    44000.0
4    90000.0
Name: total_amount, dtype: float64

In [28]:
before = len(df)
df = df[(df['quantity'] > 0) & (df['unit_price'] > 0)]
print(f'Rows: {before} -> {len(df)} (removed {before - len(df)})')

Rows: 30 -> 30 (removed 0)

In [ ]:
print(f'Original: {len(raw_df)} rows')
print(f'Cleaned: {len(df)} rows')
print(f'Removed: {len(raw_df) - len(df)}')
print(f'Nulls: {df.isnull().sum().sum()}')
print(f'Dupes: {df.duplicated().sum()}')

Original rows: 30
Cleaned rows: 30
Removed: 0
Missing: 0
Duplicates: 0
Data is clean

In [ ]:
summary = df.groupby('category').agg(
    orders=('order_id', 'count'),
    total=('total_amount', 'sum'),
    avg=('total_amount', 'mean')
).round(2).sort_values('total', ascending=False)
print(summary)

Sales by Category:
   category  orders  total_sales  avg_order  max_order
Electronics      16     697800.0   43612.50   135000.0
Accessories      13      76200.0    5861.54     9000.0
      Other       1      44000.0   44000.00    44000.0

In [29]:
print(f'Orders: {len(df)}')
print(f'Revenue: Rs {df["total_amount"].sum():,.0f}')
print(f'Average: Rs {df["total_amount"].mean():,.0f}')
print(f'Median: Rs {df["total_amount"].median():,.0f}')

Orders: 30
Revenue: Rs 818,000
Average: Rs 27,267
Median: Rs 8,000

In [ ]:
df.to_excel('sales_data_cleaned.xlsx', index=False)
print(f'Exported: sales_data_cleaned.xlsx ({len(df)} rows)')

Cleaned data exported
  * sales_data_cleaned.xlsx (30 rows)

In [ ]:
display(df[['order_id', 'customer_name', 'product', 'category', 'quantity', 'unit_price', 'total_amount']].head(10))

Sample of cleaned data:

,order_id,customer_name,product,category,quantity,unit_price,total_amount
0,1001,Ramesh Kumar,Laptop,Electronics,2.0,45000,90000.0
1,1002,Priya Nair,Unknown Product,Electronics,1.0,15000,15000.0
2,1003,AMIT VERMA,Keyboard,Accessories,3.0,1200,3600.0
3,1004,Sunita Patel,Monitor,Electronics,2.0,22000,44000.0
4,1005,Ramesh Kumar,Laptop,Electronics,2.0,45000,90000.0
5,1006,kiran mehta,Mouse,Accessories,10.0,800,8000.0
6,1007,Deepak Singh,Headphones,Electronics,2.0,3500,7000.0
7,1008,Unknown Customer,Webcam,Accessories,1.0,2500,2500.0
8,1009,Ananya Das,Laptop,Electronics,1.0,45000,45000.0
9,1010,Vikram Iyer,Keyboard,Accessories,5.0,1200,6000.0
10,1011,Pooja Gupta,Monitor,Electronics,2.0,22000,44000.0
11,1012,SURESH RAO,USB Hub,Accessories,8.0,600,4800.0
12,1013,Meera Joshi,Laptop,Electronics,2.0,45000,90000.0
13,1014,Arjun Nair,Headphones,Electronics,3.0,3500,10500.0
14,1015,Tanvi Mehta,Webcam,Accessories,2.0,2500,5000.0

Shape: 30 rows by 10 columns
Quality: 0 nulls, 0 dupes